### ISSUE TITLE
登录失败

### ISSUE THREAD

**Issue by lizr2004** [Leohh123/Todolist#2]
username: lizr
password: 不告诉你

**Comment by Leohh123** [comment]
换Chrome

**Comment by lizr2004** [comment]
chromium 不行吗?
```
chromium 70.0.3538.77-2
google-chrome 70.0.3538.102-1
```

**Comment by Leohh123** [comment]
我的chromium可以啊
你发下refresh.php的headers
我大概知道为啥了QAQ......

**Comment by Leohh123** [comment]
bug++:
我那个sb token发送方式在不同浏览器里执行顺序不一样
然后就乱了
等周末我改成localStorage存token，post: data发送en_token

**Comment by lizr2004** [comment]
token=FhdqMVrHbm5mWE0NiuOVhDReshqL/dpeJHffvY4YgeQ%3D

但是开左上角那个cookie就没有token了

![image](https://user-images.githubusercontent.com/32995118/48659068-d8494d80-ea86-11e8-8523-3de1e2a36b41.png)

**Comment by lizr2004** [comment]
[ClickME](http://leohh.xyz/tools/timer/)

这个算issue吗?

**Comment by Leohh123** [comment]
不算吧2333

**Comment by Leohh123** [comment]
另外：bug fixed
（部分浏览器在登录后可能需要刷新一下才行）
